# Generated by Django 5.2.13 on 2026-04-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('forex_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
