# Generated by Django 5.2.13 on 2026-04-21 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='Gold Bar', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('actual_process_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('second_process_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('process_loss', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('density', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('actual_product_quality', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quantity_grams', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('uom', models.CharField(default='g', max_length=50)),
                ('discount_addition', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_ugx', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='branches.branch')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
