# Generated by Django 5.2.13 on 2026-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='net_payable',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_grams',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='uom',
        ),
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='conversion_market_unit',
            field=models.DecimalField(decimal_places=4, default=0.38, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='expected_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='market_price_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='market_price_unit',
            field=models.CharField(default='g', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_ref',
            field=models.CharField(default='Paid Unfixed Amount', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='purchase_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_unit',
            field=models.CharField(default='t', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='x_factor',
            field=models.DecimalField(decimal_places=4, default=92.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='actual_product_quality',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
