# Generated by Django 5.2.13 on 2026-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_manual_first_process_sale_manual_purity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='density',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
