# Generated by Django 5.2.13 on 2026-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_actual_process_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='frontend_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='material_unit_input',
            field=models.CharField(default='Grams', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='market_price_unit',
            field=models.CharField(default='oz', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.CharField(default='RM', max_length=255),
        ),
    ]
