# Generated by Django 5.2.13 on 2026-04-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Branch Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
