# Generated by Django 5.2.13 on 2026-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('smaller', 'Smaller than reference'), ('reference', 'Reference Unit'), ('bigger', 'Bigger than reference')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='x_factor',
            field=models.DecimalField(decimal_places=4, default=92.0, max_digits=12),
        ),
    ]
