# Generated by Django 5.2.13 on 2026-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('GOLD_PURCHASE', 'Gold Purchase'), ('BRANCH_EXPENSE', 'Branch Expense'), ('OTHER', 'Other Expense')], default='GOLD_PURCHASE', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='grams',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
